# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '/OfficeMapUI/'
    customCommand: 'install -g @angular/cli'
  displayName: 'npm install -g @angular/cli'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '/OfficeMapUI/'
  displayName: 'npm install'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '/OfficeMapUI/'
    customCommand: 'run build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students (c269c9fc-f193-4c36-b558-87a3a74dafd5)'
    appType: 'webApp'
    WebAppName: 'angular-deployment'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(System.DefaultWorkingDirectory)'