
# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'
  
variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  
steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    displayName: 'Nuget restore'
    inputs:
      restoreSolution: '$(solution)'
      
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: restore
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
      command: 'build'
      arguments: '--no-restore --configuration $(buildConfiguration)'
      projects: $(solution)

  - task: DotNetCoreCLI@2
    displayName:  'Publish the projects - $(buildConfiguration)'
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      zipAfterPublish: true
      arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts.'
    inputs:
     pathtoPublish: $(Build.ArtifactStagingDirectory)
     artifactName: 'OfficeMapApi.Drop' 
