# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

variables:
  project: 'UserService/UserService.csproj'
  tests: '**/*.Tests.csproj' 
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(project)

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: $(project)

- task: DotNetCoreCLI@2
  displayName: 'Test project'
  inputs:
    command: 'test'
    projects: $(tests)
    
- task: DotNetCoreCLI@2
  displayName:  'Publish the project - $(buildConfiguration)'
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts.'
  inputs:
   pathtoPublish: $(Build.ArtifactStagingDirectory)
   artifactName: 'UserService.Drop'
