// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkplaceService.Database;

namespace WorkplaceService.Migrations
{
    [DbContext(typeof(WorkplaceServiceDbContext))]
    [Migration("20200508075632_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkplaceService.Database.Entities.MapFile", b =>
                {
                    b.Property<int>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("binary(50)")
                        .IsFixedLength(true)
                        .HasMaxLength(50);

                    b.Property<Guid>("MapGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MapGUID")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Obsolete")
                        .HasColumnType("bit");

                    b.HasKey("MapId")
                        .HasName("PK_Maps");

                    b.ToTable("MapFiles");
                });

            modelBuilder.Entity("WorkplaceService.Database.Entities.Workplace", b =>
                {
                    b.Property<int>("WorkplaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("MapId")
                        .HasColumnType("int");

                    b.Property<bool>("Obsolete")
                        .HasColumnType("bit");

                    b.Property<int?>("SpaceId")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkplaceGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("WorkplaceGUID")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.HasKey("WorkplaceId")
                        .HasName("PK_Workplace");

                    b.HasIndex("MapId");

                    b.ToTable("Workplaces");
                });

            modelBuilder.Entity("WorkplaceService.Database.Entities.Workplace", b =>
                {
                    b.HasOne("WorkplaceService.Database.Entities.MapFile", "Map")
                        .WithMany("Workplaces")
                        .HasForeignKey("MapId")
                        .HasConstraintName("FK_Workplaces_MapFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
